package com.joy.catering.service;
import com.joy.catering.*; import com.joy.catering.dto.Dtos.*; import com.joy.catering.model.*; import com.joy.catering.repo.*; import com.joy.catering.security.JwtService;
import org.springframework.http.HttpStatus; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service; import java.nio.charset.StandardCharsets; import java.security.*; import java.time.*; import java.util.*;
@Service public class AuthService {
 private final UserRepository users; private final PasswordResetRepository resets; private final PasswordEncoder encoder; private final JwtService jwt;
 public AuthService(UserRepository u,PasswordResetRepository r,PasswordEncoder e,JwtService j){users=u;resets=r;encoder=e;jwt=j;}
 public User register(Register d){String email=d.email().trim().toLowerCase(); if(users.findByEmail(email).isPresent())throw new ApiException(HttpStatus.CONFLICT,"Email is already registered"); if(!d.password().equals(d.passwordConfirmation()))throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"Passwords do not match"); if(!d.password().matches(".*[A-Za-z].*")||!d.password().matches(".*[0-9].*"))throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"Password must contain a letter and a number");
  User u=new User();u.setEmail(email);u.setPasswordHash(encoder.encode(d.password()));CustomerProfile p=new CustomerProfile();p.setUser(u);p.setFullName(d.fullName());p.setMobileNumber(d.mobileNumber());p.setAddress(d.address());u.setProfile(p);return users.save(u);}
 public String login(Login d){User u=users.findByEmail(d.email().trim().toLowerCase()).orElse(null);if(u==null||!encoder.matches(d.password(),u.getPasswordHash())||!u.isActive())throw new ApiException(HttpStatus.UNAUTHORIZED,"Invalid email or password");return jwt.token(u);}
 public String forgot(EmailInput d,boolean enabled){if(!enabled)throw new ApiException(HttpStatus.SERVICE_UNAVAILABLE,"Password reset delivery is not configured. Contact the administrator.");User u=users.findByEmail(d.email().trim().toLowerCase()).orElse(null);byte[] bytes=new byte[32];new SecureRandom().nextBytes(bytes);String token=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);if(u!=null){PasswordReset r=new PasswordReset();r.setUser(u);r.setTokenHash(hash(token));r.setExpiresAt(OffsetDateTime.now().plusMinutes(15));resets.findByUserId(u.getId()).forEach(x->{x.setUsed(true);resets.save(x);});resets.save(r);} return token; }
 public void reset(ResetPassword d){if(!d.password().equals(d.passwordConfirmation()))throw new ApiException(HttpStatus.BAD_REQUEST,"Passwords do not match");var r=resets.findByTokenHashAndUsedFalseAndExpiresAtAfter(hash(d.token()),OffsetDateTime.now()).orElseThrow(()->new ApiException(HttpStatus.BAD_REQUEST,"Invalid or expired reset token"));User u=r.getUser();if(!u.isActive())throw new ApiException(HttpStatus.BAD_REQUEST,"Invalid or expired reset token");u.setPasswordHash(encoder.encode(d.password()));u.setTokenVersion(u.getTokenVersion()+1);users.save(u);r.setUsed(true);resets.save(r);}
 static String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new RuntimeException(e);}}
}
