package com.joy.catering.service;
import com.joy.catering.*; import com.joy.catering.dto.Dtos.*; import com.joy.catering.model.*; import com.joy.catering.repo.*; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import java.time.*; import java.util.*;
@Service public class BookingService {
 final BookingRepository bookings; final PackageRepository packages; final CatalogService catalog;
 public BookingService(BookingRepository b,PackageRepository p,CatalogService c){bookings=b;packages=p;catalog=c;}
 public Booking apply(Booking b,BookingInput d){if(!d.eventDate().isAfter(LocalDate.now(ZoneId.of("Asia/Colombo"))))throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"Event date must be after today in Sri Lanka");PackageEntity p=packages.findById(d.packageId()).orElse(null);if(p==null||!catalog.publicAvailable(p))throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"Selected package is unavailable");if(d.guestCount()<p.getMinimumGuestCount()||(p.getMaximumGuestCount()!=null&&d.guestCount()>p.getMaximumGuestCount()))throw new ApiException(HttpStatus.UNPROCESSABLE_ENTITY,"Guest count is outside the selected package limits");
  b.setPackageEntity(p);b.setPackageName(p.getName());b.setPricePerPerson(p.getPricePerPerson());b.setMenuSnapshot(p.getMenuItems().stream().map(MenuItem::getName).toList());b.setEventDate(d.eventDate());b.setEventTime(d.eventTime());b.setEventLocation(d.eventLocation());b.setGuestCount(d.guestCount());b.setSpecialRequirements(d.specialRequirements()==null?"":d.specialRequirements());return b;}
 public Booking own(Long id,Long customer){return bookings.findById(id).filter(b->customer==null||b.getCustomer().getId().equals(customer)).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Booking not found"));}
 public String reference(){return "CAT-"+LocalDate.now(ZoneId.of("Asia/Colombo")).toString().replace("-","")+ "-" + UUID.randomUUID().toString().replace("-","").substring(0,12).toUpperCase();}
 public void transition(Booking b,BookingStatus s,String actor){boolean ok=actor.equals("customer")&&((b.getStatus()==BookingStatus.PENDING||b.getStatus()==BookingStatus.APPROVED)&&s==BookingStatus.CANCELLED)||actor.equals("reviewer")&&(b.getStatus()==BookingStatus.PENDING&&(s==BookingStatus.APPROVED||s==BookingStatus.REJECTED)||(b.getStatus()==BookingStatus.APPROVED&&s==BookingStatus.COMPLETED));if(!ok)throw new ApiException(HttpStatus.CONFLICT,"Cannot change "+b.getStatus()+" to "+s);b.setStatus(s);}
}
