import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '../auth';
import { Field, LoadState, money, PageTitle, Pager, useData } from '../components';
import type { EventType, Package } from '../types';

export function Home() { return <><section className="hero"><div><p className="eyebrow">Sri Lankan hospitality, thoughtfully served</p><h1>For moments<br/>worth <em>sharing.</em></h1><p>From family celebrations to your biggest day, find a menu that brings everyone to the table.</p><Link className="button" to="/packages">Find your gathering <span aria-hidden="true">↗</span></Link><div className="hero-note">Freshly prepared · Locally inspired · Made for your occasion</div></div><div className="table-art" role="img" aria-label="Decorative overhead illustration of a place setting with a leaf on a ceramic plate"><div className="plate"><span>the joy<br/>of gathering</span><i className="leaf one"/><i className="leaf two"/><i className="leaf three"/></div><div className="cutlery">│ │</div><span className="art-caption">A place for everyone.</span></div></section><section className="steps"><div><span>01 / EXPLORE</span><h3>Find your flavour</h3><p>Discover menus for weddings, workdays and everything in between.</p></div><div><span>02 / PLAN</span><h3>Make it yours</h3><p>Tell us when, where and how many. Add the details that matter to you.</p></div><div><span>03 / CONNECT</span><h3>We’ll take a look</h3><p>Our team reviews your request. Follow its progress from your account.</p></div></section></>; }

export function PackageCard({item, index}: {item: Package; index: number}) { return <article className="package-card"><div className={`card-art tone-${index % 3}`} aria-hidden="true"><span>{item.event_type.name}</span><div className="mini-plate">✳</div></div><div className="card-body"><p className="eyebrow">{item.event_type.name} · from {item.minimum_guest_count} guests</p><h2>{item.name}</h2><p>{item.description}</p><div className="price">{money(item.price_per_person)} <small>/ guest</small></div><Link className="text-link" to={`/packages/${item.id}`}>Explore the menu <span aria-hidden="true">↗</span></Link></div></article>; }
export function PackageList() {
  const [search, setSearch] = useState(''); const [event, setEvent] = useState(''); const [page, setPage] = useState(0);
  const packages = useData<Package[]>(`/packages?search=${encodeURIComponent(search)}${event ? `&event_type=${event}` : ''}&offset=${page * 50}`);
  const events = useData<EventType[]>('/event-types');
  return <><PageTitle eyebrow="A menu for every moment" title="Find your perfect table"/><p className="intro">Comforting favourites. Generous portions. Choose a package and make the occasion your own.</p><div className="filters"><Field label="Search packages"><input type="search" placeholder="Try wedding or family…" value={search} onChange={e => {setSearch(e.target.value); setPage(0);}}/></Field><Field label="Event type"><select value={event} onChange={e => {setEvent(e.target.value); setPage(0);}}><option value="">All occasions</option>{events.data?.map(e => <option key={e.id} value={e.id}>{e.name}</option>)}</select></Field></div>{events.error && <p role="alert">Event types could not load. <button onClick={events.reload}>Retry</button></p>}<LoadState {...packages}>{packages.data?.length ? <div className="card-grid">{packages.data.map((p,i) => <PackageCard key={p.id} item={p} index={i}/>)}</div> : <div className="empty"><h2>No packages found</h2><p>Try another search or event type.</p></div>}<Pager page={page} setPage={setPage} count={packages.data?.length || 0}/></LoadState></>;
}
export function PackageDetail() {
  const {id} = useParams(); const result = useData<Package>(`/packages/${id}`); const {user} = useAuth(); const p = result.data;
  return <LoadState {...result}>{p && <><Link to="/packages" className="back">← All packages</Link><PageTitle eyebrow={p.event_type.name} title={p.name}/><div className="detail-grid"><section className="panel"><h2>A generous spread</h2><p>{p.description}</p><h3>On the menu</h3><ul className="menu-list">{p.menu_items.map(item => <li key={item.id}><div><strong>{item.name}</strong><small>{item.category}</small></div><p>{item.description}</p>{item.dietary_information && <span className="diet">{item.dietary_information}</span>}</li>)}</ul></section><aside className="panel summary"><p className="eyebrow">Made for your occasion</p><h2>{money(p.price_per_person)}</h2><p>per guest · LKR</p><hr/><p>{p.minimum_guest_count}{p.maximum_guest_count ? `–${p.maximum_guest_count}` : '+'} guests</p><p>The estimated package total is the price per guest × your guest count.</p>{(!user || user.role === 'CUSTOMER') && <Link className="button" to={`/bookings/new?package=${p.id}`}>Plan your event ↗</Link>}<small>Your request will be reviewed by our team.</small></aside></div></>}</LoadState>;
}
