package com.joy.catering.controller;
import com.joy.catering.*;import com.joy.catering.Mapping;import com.joy.catering.dto.Dtos.*;import com.joy.catering.model.*;import com.joy.catering.repo.*;import com.joy.catering.service.BookingService;import jakarta.validation.Valid;import org.springframework.http.*;import org.springframework.security.core.Authentication;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.time.*;import java.util.*;
@RestController public class BookingController {
 final BookingRepository repo;final BookingService service;public BookingController(BookingRepository r,BookingService s){repo=r;service=s;}
 User me(Authentication a){return (User)a.getPrincipal();}
 @PostMapping("/bookings") ResponseEntity<BookingOut> create(@Valid @RequestBody BookingInput d,Authentication a){User u=me(a);var b=new Booking();b.setCustomer(u);b.setReference(service.reference());service.apply(b,d);return ResponseEntity.status(201).body(Mapping.booking(repo.save(b)));}
 @GetMapping("/bookings") List<BookingOut> own(Authentication a){return repo.findByCustomerIdOrderByCreatedAtDescIdDesc(me(a).getId()).stream().map(Mapping::booking).toList();}
 @GetMapping("/bookings/{id}") BookingOut detail(@PathVariable Long id,Authentication a){return Mapping.booking(service.own(id,me(a).getId()));}
 @PutMapping("/bookings/{id}") BookingOut edit(@PathVariable Long id,@Valid @RequestBody BookingInput d,Authentication a){var b=service.own(id,me(a).getId());if(b.getStatus()!=BookingStatus.PENDING)throw new ApiException(HttpStatus.CONFLICT,"Only pending bookings can be edited");return Mapping.booking(repo.save(service.apply(b,d)));}
 @PostMapping("/bookings/{id}/cancel") BookingOut cancel(@PathVariable Long id,Authentication a){var b=service.own(id,me(a).getId());service.transition(b,BookingStatus.CANCELLED,"customer");return Mapping.booking(repo.save(b));}
 @GetMapping("/staff/bookings") @PreAuthorize("hasAnyRole('CUSTOMER_RELATIONS_OFFICER','ADMIN')") List<StaffBookingOut> review(@RequestParam(required=false) BookingStatus status){var list=status==null?repo.findAllByOrderByCreatedAtDescIdDesc():repo.findByStatusOrderByCreatedAtDescIdDesc(status);return list.stream().map(Mapping::staffBooking).toList();}
 @GetMapping("/staff/bookings/{id}") @PreAuthorize("hasAnyRole('CUSTOMER_RELATIONS_OFFICER','ADMIN')") StaffBookingOut reviewDetail(@PathVariable Long id){return Mapping.staffBooking(service.own(id,null));}
 @PostMapping("/staff/bookings/{id}/approve") @PreAuthorize("hasAnyRole('CUSTOMER_RELATIONS_OFFICER','ADMIN')") StaffBookingOut approve(@PathVariable Long id){var b=service.own(id,null);if(!b.getEventDate().isAfter(LocalDate.now(ZoneId.of("Asia/Colombo"))))throw new ApiException(HttpStatus.CONFLICT,"Cannot approve an event dated today or in the past");service.transition(b,BookingStatus.APPROVED,"reviewer");return Mapping.staffBooking(repo.save(b));}
 @PostMapping("/staff/bookings/{id}/reject") @PreAuthorize("hasAnyRole('CUSTOMER_RELATIONS_OFFICER','ADMIN')") StaffBookingOut reject(@PathVariable Long id,@Valid @RequestBody RejectInput d){var b=service.own(id,null);service.transition(b,BookingStatus.REJECTED,"reviewer");b.setRejectionReason(d.reason());return Mapping.staffBooking(repo.save(b));}
}
