package com.joy.catering.controller;
import com.joy.catering.*;import com.joy.catering.Mapping;import com.joy.catering.dto.Dtos.*;import com.joy.catering.model.*;import com.joy.catering.repo.*;import com.joy.catering.service.CatalogService;import jakarta.validation.Valid;import org.springframework.data.domain.*;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController public class CatalogController {
 final EventTypeRepository events;final MenuItemRepository menus;final PackageRepository packages;final CatalogService service;
 public CatalogController(EventTypeRepository e,MenuItemRepository m,PackageRepository p,CatalogService s){events=e;menus=m;packages=p;service=s;}
 @GetMapping("/event-types") List<EventTypeOut> eventTypes(){return events.findAllByOrderByNameAsc().stream().map(Mapping::event).toList();}
 @GetMapping("/menu-items") List<MenuOut> menuItems(){return menus.findByActiveTrueOrderByIdAsc().stream().map(Mapping::menu).toList();}
 @GetMapping("/packages") List<PackageOut> packages(@RequestParam(defaultValue="") String search,@RequestParam(required=false) Long eventType){return packages.findByActiveTrueOrderByIdAsc().stream().filter(service::publicAvailable).filter(p->search.isBlank()||p.getName().toLowerCase().contains(search.trim().toLowerCase())).filter(p->eventType==null||p.getEventType().getId().equals(eventType)).map(Mapping::pack).toList();}
 @GetMapping("/packages/{id}") PackageOut detail(@PathVariable Long id){var p=packages.findById(id).filter(service::publicAvailable).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Package not found or unavailable"));return Mapping.pack(p);}
 @GetMapping("/staff/menu-items") @PreAuthorize("hasAnyRole('SENIOR_CHEF','ADMIN')") List<MenuOut> allMenus(){return menus.findAllByOrderByIdAsc().stream().map(Mapping::menu).toList();}
 @PostMapping("/staff/event-types") @PreAuthorize("hasAnyRole('SENIOR_CHEF','ADMIN')") ResponseEntity<EventTypeOut> createEvent(@Valid @RequestBody EventTypeInput d){var e=new EventType();e.setName(d.name().trim());return ResponseEntity.status(201).body(Mapping.event(events.save(e)));}
 @PostMapping("/staff/menu-items") @PreAuthorize("hasAnyRole('SENIOR_CHEF','ADMIN')") ResponseEntity<MenuOut> createMenu(@Valid @RequestBody MenuInput d){var m=new MenuItem();m.setName(d.name());m.setDescription(d.description()==null?"":d.description());m.setCategory(d.category());m.setDietaryInformation(d.dietaryInformation()==null?"":d.dietaryInformation());m.setActive(d.isActive());return ResponseEntity.status(201).body(Mapping.menu(menus.save(m)));}
 @PutMapping("/staff/menu-items/{id}") @PreAuthorize("hasAnyRole('SENIOR_CHEF','ADMIN')") MenuOut updateMenu(@PathVariable Long id,@Valid @RequestBody MenuInput d){var m=menus.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"Menu item not found"));m.setName(d.name());m.setDescription(d.description()==null?"":d.description());m.setCategory(d.category());m.setDietaryInformation(d.dietaryInformation()==null?"":d.dietaryInformation());m.setActive(d.isActive());return Mapping.menu(menus.save(m));}
 @GetMapping("/staff/packages") @PreAuthorize("hasAnyRole('SENIOR_CHEF','ADMIN')") List<PackageOut> allPackages(){return packages.findAllByOrderByIdAsc().stream().map(Mapping::pack).toList();}
 @PostMapping("/staff/packages") @PreAuthorize("hasAnyRole('SENIOR_CHEF','ADMIN')") ResponseEntity<PackageOut> createPackage(@Valid @RequestBody PackageInput d){return ResponseEntity.status(201).body(Mapping.pack(service.save(d,null)));}
 @PutMapping("/staff/packages/{id}") @PreAuthorize("hasAnyRole('SENIOR_CHEF','ADMIN')") PackageOut updatePackage(@PathVariable Long id,@Valid @RequestBody PackageInput d){return Mapping.pack(service.save(d,id));}
}
