package com.joy.catering.controller;
import com.joy.catering.*;import com.joy.catering.dto.Dtos.*;import com.joy.catering.model.*;import com.joy.catering.repo.*;import jakarta.validation.Valid;import org.springframework.http.*;import org.springframework.security.access.prepost.PreAuthorize;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;import java.util.*;
@RestController public class UserController {
 final UserRepository users;final ProfileRepository profiles;public UserController(UserRepository u,ProfileRepository p){users=u;profiles=p;}
 @GetMapping("/customers/me/profile") @PreAuthorize("hasRole('CUSTOMER')") ProfileOut profile(Authentication a){return Mapping.profile(((User)a.getPrincipal()).getProfile());}
 @PutMapping("/customers/me/profile") @PreAuthorize("hasRole('CUSTOMER')") ProfileOut update(@Valid @RequestBody ProfileInput d,Authentication a){var p=((User)a.getPrincipal()).getProfile();p.setFullName(d.fullName());p.setMobileNumber(d.mobileNumber());p.setAddress(d.address());return Mapping.profile(profiles.save(p));}
 @GetMapping("/admin/users") @PreAuthorize("hasRole('ADMIN')") List<UserOut> users(){return users.findAllByOrderByIdAsc().stream().map(Mapping::user).toList();}
 @PutMapping("/admin/users/{id}") @PreAuthorize("hasRole('ADMIN')") UserOut updateUser(@PathVariable Long id,@Valid @RequestBody UserUpdate d,Authentication a){User admin=(User)a.getPrincipal();if(id.equals(admin.getId()))throw new ApiException(HttpStatus.CONFLICT,"Use another administrator to change your own access");User u=users.findById(id).orElseThrow(()->new ApiException(HttpStatus.NOT_FOUND,"User not found"));if((u.getRole()==Role.CUSTOMER)!=(d.role()==Role.CUSTOMER))throw new ApiException(HttpStatus.CONFLICT,"Customer and staff identities cannot be converted; create a separate staff account");u.setRole(d.role());u.setActive(d.isActive());u.setTokenVersion(u.getTokenVersion()+1);return Mapping.user(users.save(u));}
}
