CREATE TABLE resources(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    name VARCHAR(120) NOT NULL,
    category VARCHAR(40) NOT NULL,
    quantity_available INTEGER NOT NULL CHECK(quantity_available >= 0),
    notes VARCHAR(500)
);

CREATE TABLE event_resource_allocations(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    event_id BIGINT NOT NULL REFERENCES scheduling_events(id),
    resource_id BIGINT NOT NULL REFERENCES resources(id),
    quantity_allocated INTEGER NOT NULL CHECK(quantity_allocated > 0),
    notes VARCHAR(500),
    UNIQUE(event_id, resource_id)
);

CREATE INDEX idx_allocation_event ON event_resource_allocations(event_id);
CREATE INDEX idx_allocation_resource ON event_resource_allocations(resource_id);
